[project]
name = "liars-dice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=<3.13"
dependencies = ["matplotlib>=3.8.0"]

[dependency-groups]
dev = [
    "lefthook>=2.0.2",
]
